[package]
name = "tux-io-encoding-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "A CLI tool for debugging and working with TuxIO files."

[dependencies]
